apiVersion: v2
name: ldapmanager
description: cloud-native LDAP management service with a web interface.
home: https://github.com/romnn/ldap-manager
icon: https://romnn.github.io/ldap-manager/icon/icon_lg.jpg
keywords:
  - ldap
  - openldap
  - user-management
  - web

type: application

version: v0.0.50

appVersion: v0.0.50

sources:
  - https://github.com/romnn/ldap-manager

maintainers:
  - name: romnn
    url: https://github.com/romnn/

dependencies:
  - name: openldap
    version: ">=0.0.0"
    condition: openldap.enabled
